import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

import Layout from '../components/layout';
import axios from 'axios';

function Home() {

  return (
    <Layout>
      <Head>
        <title>Dungeons and Dragons API Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.homepage}>
        <Link href={`/races/`}><a style={{display: "block"}} className={styles.card} >Browse Races</a></Link>
        <Link href={`/spells/`}><a style={{display: "block"}} className={styles.card} >Browse Spells</a></Link>
        
    </div>
    
    </Layout>
  )
}

// loadGetInitialProps = async (ctx) => {
//   console.log(ctx);
// }

export default Home;
