import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import lambdaURL from '../lambdaURL';

import Layout from '../components/layout';
import axios from 'axios';

export default function Home() {

  const [races,setRaces] = useState([]);
  const [raceName, setRaceName]  = useState("");
  const [alignment, setAlignment]  = useState("");
  const [age, setAge]  = useState("");
  const [size, setSize]  = useState("");
  const [language, setLanguage]  = useState("");

  useEffect(() => {
      axios.get(`${lambdaURL}/races/`).then(res => {
      setRaces(res.data[0].results);
      setAlignment(res.data[1].alignment);
      setRaceName(res.data[1].name);
      setAge(res.data[1].age);
      setSize(res.data[1].size_description);
      setLanguage(res.data[1].language_desc);
    })
  }, []);

  const selectRace = (el) => {
      axios.get(`${lambdaURL}/races/${el}`).then(res => {
      setAlignment(res.data.alignment);
      setRaceName(res.data.name);
      setAge(res.data.age);
      setSize(res.data.size_description);
      setLanguage(res.data.language_desc);
    });
  }

  // Mapping out the API response in a separate function instead of on the main render in case of errors on the API call.
  const RaceList = () => {
    if (races !== undefined) {
      return races.map(race => {
      return <a className={styles.card} key={race.index} style={{display: "block"}} onClick={() => selectRace(race.index)}>{race.name}</a>
    })}
    else {
      return <div>Sorry, an error has occurred!</div>
    }
  }

  return (
    <Layout>
      <Head>
        <title>Dungeons and Dragons API Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.mainCard}>
        <h3>{raceName}</h3>
        <p><b>Alignment:</b>{" "}{alignment}</p>
        <p><b>Age:</b>{" "}{age}</p>
        <p><b>Size:</b>{" "}{size}</p>
        <p><b>Languages:</b>{" "}{language}</p>
    </div>
    <h4 style={{textAlign: "center"}}>More Races</h4>
    <div className={styles.linkContainer}>
      <RaceList />
    </div>
    
    </Layout>
  )
}
