import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';

import Layout from '../components/layout';
import axios from 'axios';
import lambdaURL from '../lambdaURL';

export default function Home() {

  const [spells,setSpells] = useState([]);
  const [spellName, setSpellName]  = useState("");
  const [desc, setDesc]  = useState("");
  const [higher, setHigher]  = useState("");
  const [range, setRange]  = useState("");
  const [level, setLevel]  = useState("");

  useEffect(() => {
      axios.get(`${lambdaURL}/spells`).then(res => {
      setSpells(res.data[0].results);
      setSpellName(res.data[1].name);
      setDesc(res.data[1].desc);
      setHigher(res.data[1].higher_level);
      setRange(res.data[1].range);
      setLevel(res.data[1].level);
    })
  }, []);

  const selectSpell = (el) => {
      axios.get(`${lambdaURL}/spells/${el}`).then(res => {
        setSpellName(res.data.name);
        setDesc(res.data.desc);
        setHigher(res.data.higher_level);
        setRange(res.data.range);
        setLevel(res.data.level);
    });
  }

  // Not all Spells have a Higher Level feature, so this is a way to hide that spot on the UI.
  const HigherLevel = () => {
      if (higher === undefined) {
          return <></>
      }
      else {
        return <p><b>At Higher Levels:</b>{" "}{higher}</p>;
      }
  }

  // Mapping out the API response in a separate function instead of on the main render in case of errors on the API call.
  const SpellList = () => {
    if (spells !== undefined) {
      return spells.map(spell => {
      return <a className={styles.card} key={spell.index} style={{display: "block"}} onClick={() => selectSpell(spell.index)}>{spell.name}</a>
    })
  }
  else {
    return <div>Sorry, an error has occurred!</div>
  }
  }

  return (
    <Layout>
      <Head>
        <title>Dungeons and Dragons API Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.mainCard}>
        <h3>{spellName}</h3>
        <p><em>{desc}</em></p>
        <p><b>Level:</b>{" "}{level}</p>
        <p><b>Range:</b>{" "}{range}</p>
        {<HigherLevel />}
        
    </div>
    <h4 style={{textAlign: "center"}}>More Spells</h4>
    <div className={styles.linkContainer}>
      <SpellList />
    </div>
    
    </Layout>
  )
}
